#!/bin/bash
#
# bootstrap installs things.

function ubuntuTerminalSetup() {
	source ~/.dotfiles/installscript
}


echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: ' reply

sudo -v #ask password beforehand

if [[ $reply =~ ^[Yy]$ ]]
then
  PS3="Select Operating System: "
  options=("Ubuntu" "MacOS" "Exit")
  select opt in "${options[@]}"; do
    case $x in
      "Ubuntu")
        ubuntuTerminalSetup
        ;;
      "MacOS")
        echo "Macintosh"
        ;;
      "Exit")
        break
        exit 0;
        ;;
      *) echo "invalid option: $REPLY" && exit 0;;
    esac
  done
fi