#!/bin/bash
#
# bootstrap installs things.

function ubuntuTerminalSetup() {
	source ~/.dotfiles/installscript
}


echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: ' reply

sudo -v #ask password beforehand

if [[ $reply =~ ^[Yy]$ ]]
then
   ubuntuTerminalSetup
fi